name: ci

on: [pull_request]

jobs:

  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: "Check git conflicts"
      run:
        git remote add upstream https://github.com/pingcap/docs-dm.git;
        git fetch upstream;
        python3 ./hack/check-conflicts.py $(git diff-tree --name-only --no-commit-id -r upstream/master...HEAD -- 'zh/' 'en/' '.md' ':(exclude).github/*')
    - name: Markdown lint
      uses: avto-dev/markdown-lint@v1
      with:
        config: './.markdownlint.yaml'
        args: '.'
    - name: Verify internal links
      run: ./hack/verify-links.sh
    - name: Verify internal link anchors
      run: ./hack/verify-link-anchors.sh
    - name: "Check unclosed tags"
      run:
        echo "checked files are $(git diff-tree --name-only --no-commit-id -r upstream/master...HEAD -- 'zh/' 'en/' '.md' ':(exclude).github/*')";
        python3 ./hack/check-tags.py $(git diff-tree --name-only --no-commit-id -r upstream/master...HEAD -- 'zh/' 'en/' '.md' ':(exclude).github/*')
    - name: Vale Linter
      uses: errata-ai/vale-action@v1.3.0
      with:
        # Optional
        styles: |
          https://github.com/errata-ai/Google/releases/latest/download/Google.zip

        # Optional
        config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini

        # Optional
        files: ../../en
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

